# Generated by Django 4.1.3 on 2022-11-24 08:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todo',
            name='Date',
        ),
    ]
